# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
target 'Mixer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'React', :path => '../js/node_modules/react-native', :subspecs => [
  'Core',
  'RCTImage',
  'RCTNetwork',
  'RCTText',
  'RCTWebSocket',
]
  # Pods for Mixer

end
